apiVersion: v1
kind: Service
metadata:
  name: {{ include "susecon-agent.backendFullname" . }}
  labels:
    {{- include "susecon-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "susecon-agent.backendSelectorLabels" . | nindent 4 }}
